/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectorRouteRouteImport } from './routes/director/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as CompanyNotFoundIndexRouteImport } from './routes/company-not-found/index'
import { Route as CollaboratorIndexRouteImport } from './routes/collaborator/index'
import { Route as DirectorDashboardRouteRouteImport } from './routes/director/dashboard/route'
import { Route as DirectorDashboardIndexRouteImport } from './routes/director/dashboard/index'
import { Route as DirectorDashboardSectorsIndexRouteImport } from './routes/director/dashboard/sectors/index'
import { Route as DirectorDashboardGoalIndexRouteImport } from './routes/director/dashboard/goal/index'
import { Route as DirectorDashboardCollaboratorsIndexRouteImport } from './routes/director/dashboard/collaborators/index'

const DirectorRouteRoute = DirectorRouteRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyNotFoundIndexRoute = CompanyNotFoundIndexRouteImport.update({
  id: '/company-not-found/',
  path: '/company-not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaboratorIndexRoute = CollaboratorIndexRouteImport.update({
  id: '/collaborator/',
  path: '/collaborator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorDashboardRouteRoute = DirectorDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorDashboardIndexRoute = DirectorDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectorDashboardRouteRoute,
} as any)
const DirectorDashboardSectorsIndexRoute =
  DirectorDashboardSectorsIndexRouteImport.update({
    id: '/sectors/',
    path: '/sectors/',
    getParentRoute: () => DirectorDashboardRouteRoute,
  } as any)
const DirectorDashboardGoalIndexRoute =
  DirectorDashboardGoalIndexRouteImport.update({
    id: '/goal/',
    path: '/goal/',
    getParentRoute: () => DirectorDashboardRouteRoute,
  } as any)
const DirectorDashboardCollaboratorsIndexRoute =
  DirectorDashboardCollaboratorsIndexRouteImport.update({
    id: '/collaborators/',
    path: '/collaborators/',
    getParentRoute: () => DirectorDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/director': typeof DirectorRouteRouteWithChildren
  '/director/dashboard': typeof DirectorDashboardRouteRouteWithChildren
  '/collaborator': typeof CollaboratorIndexRoute
  '/company-not-found': typeof CompanyNotFoundIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/director/dashboard/': typeof DirectorDashboardIndexRoute
  '/director/dashboard/collaborators': typeof DirectorDashboardCollaboratorsIndexRoute
  '/director/dashboard/goal': typeof DirectorDashboardGoalIndexRoute
  '/director/dashboard/sectors': typeof DirectorDashboardSectorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/director': typeof DirectorRouteRouteWithChildren
  '/collaborator': typeof CollaboratorIndexRoute
  '/company-not-found': typeof CompanyNotFoundIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/director/dashboard': typeof DirectorDashboardIndexRoute
  '/director/dashboard/collaborators': typeof DirectorDashboardCollaboratorsIndexRoute
  '/director/dashboard/goal': typeof DirectorDashboardGoalIndexRoute
  '/director/dashboard/sectors': typeof DirectorDashboardSectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/director': typeof DirectorRouteRouteWithChildren
  '/director/dashboard': typeof DirectorDashboardRouteRouteWithChildren
  '/collaborator/': typeof CollaboratorIndexRoute
  '/company-not-found/': typeof CompanyNotFoundIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/director/dashboard/': typeof DirectorDashboardIndexRoute
  '/director/dashboard/collaborators/': typeof DirectorDashboardCollaboratorsIndexRoute
  '/director/dashboard/goal/': typeof DirectorDashboardGoalIndexRoute
  '/director/dashboard/sectors/': typeof DirectorDashboardSectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/director'
    | '/director/dashboard'
    | '/collaborator'
    | '/company-not-found'
    | '/sign-in'
    | '/director/dashboard/'
    | '/director/dashboard/collaborators'
    | '/director/dashboard/goal'
    | '/director/dashboard/sectors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/director'
    | '/collaborator'
    | '/company-not-found'
    | '/sign-in'
    | '/director/dashboard'
    | '/director/dashboard/collaborators'
    | '/director/dashboard/goal'
    | '/director/dashboard/sectors'
  id:
    | '__root__'
    | '/'
    | '/director'
    | '/director/dashboard'
    | '/collaborator/'
    | '/company-not-found/'
    | '/sign-in/'
    | '/director/dashboard/'
    | '/director/dashboard/collaborators/'
    | '/director/dashboard/goal/'
    | '/director/dashboard/sectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectorRouteRoute: typeof DirectorRouteRouteWithChildren
  CollaboratorIndexRoute: typeof CollaboratorIndexRoute
  CompanyNotFoundIndexRoute: typeof CompanyNotFoundIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-not-found/': {
      id: '/company-not-found/'
      path: '/company-not-found'
      fullPath: '/company-not-found'
      preLoaderRoute: typeof CompanyNotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborator/': {
      id: '/collaborator/'
      path: '/collaborator'
      fullPath: '/collaborator'
      preLoaderRoute: typeof CollaboratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director/dashboard': {
      id: '/director/dashboard'
      path: '/dashboard'
      fullPath: '/director/dashboard'
      preLoaderRoute: typeof DirectorDashboardRouteRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/dashboard/': {
      id: '/director/dashboard/'
      path: '/'
      fullPath: '/director/dashboard/'
      preLoaderRoute: typeof DirectorDashboardIndexRouteImport
      parentRoute: typeof DirectorDashboardRouteRoute
    }
    '/director/dashboard/sectors/': {
      id: '/director/dashboard/sectors/'
      path: '/sectors'
      fullPath: '/director/dashboard/sectors'
      preLoaderRoute: typeof DirectorDashboardSectorsIndexRouteImport
      parentRoute: typeof DirectorDashboardRouteRoute
    }
    '/director/dashboard/goal/': {
      id: '/director/dashboard/goal/'
      path: '/goal'
      fullPath: '/director/dashboard/goal'
      preLoaderRoute: typeof DirectorDashboardGoalIndexRouteImport
      parentRoute: typeof DirectorDashboardRouteRoute
    }
    '/director/dashboard/collaborators/': {
      id: '/director/dashboard/collaborators/'
      path: '/collaborators'
      fullPath: '/director/dashboard/collaborators'
      preLoaderRoute: typeof DirectorDashboardCollaboratorsIndexRouteImport
      parentRoute: typeof DirectorDashboardRouteRoute
    }
  }
}

interface DirectorDashboardRouteRouteChildren {
  DirectorDashboardIndexRoute: typeof DirectorDashboardIndexRoute
  DirectorDashboardCollaboratorsIndexRoute: typeof DirectorDashboardCollaboratorsIndexRoute
  DirectorDashboardGoalIndexRoute: typeof DirectorDashboardGoalIndexRoute
  DirectorDashboardSectorsIndexRoute: typeof DirectorDashboardSectorsIndexRoute
}

const DirectorDashboardRouteRouteChildren: DirectorDashboardRouteRouteChildren =
  {
    DirectorDashboardIndexRoute: DirectorDashboardIndexRoute,
    DirectorDashboardCollaboratorsIndexRoute:
      DirectorDashboardCollaboratorsIndexRoute,
    DirectorDashboardGoalIndexRoute: DirectorDashboardGoalIndexRoute,
    DirectorDashboardSectorsIndexRoute: DirectorDashboardSectorsIndexRoute,
  }

const DirectorDashboardRouteRouteWithChildren =
  DirectorDashboardRouteRoute._addFileChildren(
    DirectorDashboardRouteRouteChildren,
  )

interface DirectorRouteRouteChildren {
  DirectorDashboardRouteRoute: typeof DirectorDashboardRouteRouteWithChildren
}

const DirectorRouteRouteChildren: DirectorRouteRouteChildren = {
  DirectorDashboardRouteRoute: DirectorDashboardRouteRouteWithChildren,
}

const DirectorRouteRouteWithChildren = DirectorRouteRoute._addFileChildren(
  DirectorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectorRouteRoute: DirectorRouteRouteWithChildren,
  CollaboratorIndexRoute: CollaboratorIndexRoute,
  CompanyNotFoundIndexRoute: CompanyNotFoundIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
