/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as CompanyNotFoundIndexRouteImport } from './routes/company-not-found/index'
import { Route as AccessDeniedIndexRouteImport } from './routes/access-denied/index'
import { Route as DashboardSegmentsIndexRouteImport } from './routes/dashboard/segments/index'
import { Route as DashboardSectorsIndexRouteImport } from './routes/dashboard/sectors/index'
import { Route as DashboardGoalsIndexRouteImport } from './routes/dashboard/goals/index'
import { Route as DashboardGoalsCollaboratorIndexRouteImport } from './routes/dashboard/goals-collaborator/index'
import { Route as DashboardCollaboratorsIndexRouteImport } from './routes/dashboard/collaborators/index'
import { Route as DashboardBrandsIndexRouteImport } from './routes/dashboard/brands/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyNotFoundIndexRoute = CompanyNotFoundIndexRouteImport.update({
  id: '/company-not-found/',
  path: '/company-not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedIndexRoute = AccessDeniedIndexRouteImport.update({
  id: '/access-denied/',
  path: '/access-denied/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSegmentsIndexRoute = DashboardSegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSectorsIndexRoute = DashboardSectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGoalsIndexRoute = DashboardGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGoalsCollaboratorIndexRoute =
  DashboardGoalsCollaboratorIndexRouteImport.update({
    id: '/goals-collaborator/',
    path: '/goals-collaborator/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCollaboratorsIndexRoute =
  DashboardCollaboratorsIndexRouteImport.update({
    id: '/collaborators/',
    path: '/collaborators/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBrandsIndexRoute = DashboardBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedIndexRoute
  '/company-not-found': typeof CompanyNotFoundIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/dashboard/brands': typeof DashboardBrandsIndexRoute
  '/dashboard/collaborators': typeof DashboardCollaboratorsIndexRoute
  '/dashboard/goals-collaborator': typeof DashboardGoalsCollaboratorIndexRoute
  '/dashboard/goals': typeof DashboardGoalsIndexRoute
  '/dashboard/sectors': typeof DashboardSectorsIndexRoute
  '/dashboard/segments': typeof DashboardSegmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedIndexRoute
  '/company-not-found': typeof CompanyNotFoundIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/dashboard/brands': typeof DashboardBrandsIndexRoute
  '/dashboard/collaborators': typeof DashboardCollaboratorsIndexRoute
  '/dashboard/goals-collaborator': typeof DashboardGoalsCollaboratorIndexRoute
  '/dashboard/goals': typeof DashboardGoalsIndexRoute
  '/dashboard/sectors': typeof DashboardSectorsIndexRoute
  '/dashboard/segments': typeof DashboardSegmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/access-denied/': typeof AccessDeniedIndexRoute
  '/company-not-found/': typeof CompanyNotFoundIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/dashboard/brands/': typeof DashboardBrandsIndexRoute
  '/dashboard/collaborators/': typeof DashboardCollaboratorsIndexRoute
  '/dashboard/goals-collaborator/': typeof DashboardGoalsCollaboratorIndexRoute
  '/dashboard/goals/': typeof DashboardGoalsIndexRoute
  '/dashboard/sectors/': typeof DashboardSectorsIndexRoute
  '/dashboard/segments/': typeof DashboardSegmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/access-denied'
    | '/company-not-found'
    | '/sign-in'
    | '/dashboard/brands'
    | '/dashboard/collaborators'
    | '/dashboard/goals-collaborator'
    | '/dashboard/goals'
    | '/dashboard/sectors'
    | '/dashboard/segments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/access-denied'
    | '/company-not-found'
    | '/sign-in'
    | '/dashboard/brands'
    | '/dashboard/collaborators'
    | '/dashboard/goals-collaborator'
    | '/dashboard/goals'
    | '/dashboard/sectors'
    | '/dashboard/segments'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/access-denied/'
    | '/company-not-found/'
    | '/sign-in/'
    | '/dashboard/brands/'
    | '/dashboard/collaborators/'
    | '/dashboard/goals-collaborator/'
    | '/dashboard/goals/'
    | '/dashboard/sectors/'
    | '/dashboard/segments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AccessDeniedIndexRoute: typeof AccessDeniedIndexRoute
  CompanyNotFoundIndexRoute: typeof CompanyNotFoundIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-not-found/': {
      id: '/company-not-found/'
      path: '/company-not-found'
      fullPath: '/company-not-found'
      preLoaderRoute: typeof CompanyNotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied/': {
      id: '/access-denied/'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/segments/': {
      id: '/dashboard/segments/'
      path: '/segments'
      fullPath: '/dashboard/segments'
      preLoaderRoute: typeof DashboardSegmentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sectors/': {
      id: '/dashboard/sectors/'
      path: '/sectors'
      fullPath: '/dashboard/sectors'
      preLoaderRoute: typeof DashboardSectorsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/goals/': {
      id: '/dashboard/goals/'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof DashboardGoalsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/goals-collaborator/': {
      id: '/dashboard/goals-collaborator/'
      path: '/goals-collaborator'
      fullPath: '/dashboard/goals-collaborator'
      preLoaderRoute: typeof DashboardGoalsCollaboratorIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/collaborators/': {
      id: '/dashboard/collaborators/'
      path: '/collaborators'
      fullPath: '/dashboard/collaborators'
      preLoaderRoute: typeof DashboardCollaboratorsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/brands/': {
      id: '/dashboard/brands/'
      path: '/brands'
      fullPath: '/dashboard/brands'
      preLoaderRoute: typeof DashboardBrandsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardBrandsIndexRoute: typeof DashboardBrandsIndexRoute
  DashboardCollaboratorsIndexRoute: typeof DashboardCollaboratorsIndexRoute
  DashboardGoalsCollaboratorIndexRoute: typeof DashboardGoalsCollaboratorIndexRoute
  DashboardGoalsIndexRoute: typeof DashboardGoalsIndexRoute
  DashboardSectorsIndexRoute: typeof DashboardSectorsIndexRoute
  DashboardSegmentsIndexRoute: typeof DashboardSegmentsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBrandsIndexRoute: DashboardBrandsIndexRoute,
  DashboardCollaboratorsIndexRoute: DashboardCollaboratorsIndexRoute,
  DashboardGoalsCollaboratorIndexRoute: DashboardGoalsCollaboratorIndexRoute,
  DashboardGoalsIndexRoute: DashboardGoalsIndexRoute,
  DashboardSectorsIndexRoute: DashboardSectorsIndexRoute,
  DashboardSegmentsIndexRoute: DashboardSegmentsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AccessDeniedIndexRoute: AccessDeniedIndexRoute,
  CompanyNotFoundIndexRoute: CompanyNotFoundIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
